travis:
  secure:
    BINSTAR_TOKEN: BCy/vumCDiHqckPKGUADvh8MH5chZZJLHJJHsWEbMPXyqv7WNQy4TWnW8eky/150KX65Jhmr5DJ+Ozj7LDRaMB7iJRVUWkohDrgRKAwAeaywkkdetuG64p8mdKAq4Uh1MZypl1gqwdS7+ppJ+eVvuch+19CHKPmcK//Gs14K97XnOULEMYv9pRDH8eJWyVXIt4HjlqtXssQzNpbKNn2aFie1xMceMH1HY6ki18BEGm218szRRSrRsKgVfpQJQ3uvVtadBL6E8yPlsQX1rx+rZRuWfzl3wbCmLmxJnH/ggOlYjWtais/QhUEHXn4yBEEpgfEMN6VyQ2xeF+ubtPLUUgRb3BoQkqasmMcBrSUcH2myC43EE8+KTLGV6aUmY3/mcwQFeZ3KdbjjEcwb+FPN2mPTztuOa65FkP8/vDISF2mBu7Q6seSs9Be7b+sQo57r8UxwOqLHn2BLmD4CkIUriI76d+t4DPrqwj/Fm2ILTIuGxFaPuR/XuNXheVHmb9jwwOlpCvgyeOHJ1dLEsWLrmpgfjZ5XIrsZdqUZxHtWDBSEkRcW0E5TiwcZ9h2vwNHP9gLl29u+JHABd8BCmeYbXbMGqwTgFoPYbD43wLMBxeN5ICyENjEe6MQhbTlMQ3IDKbozFCAjrqN72gDrjSWcMoAYPavHJ31Ln6rglFtNT04=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
