travis:
  secure:
    BINSTAR_TOKEN: j/RVXRrKJvZNdmPu+5Y5klY4Dc1cH44q9lcWmCOZESLQwXBZ7QyD0YY/hboP6GL8gT8UYjJqB1JfeuOsgooc/vC16LSmf1eQzhZ/+irYousTAE22CTZK0RVpc9GwRTYf7hmlU2St900h+tY49DyxxTWRHaECikSCsbUPLpKlFq5aGGq/vAg7x6pB7vmOLQmnR3PW1K8uEXfM0MAp5uO6LU2VpcEQapjJZ+OrU5SyWXz/vmjVBAMU2/of5kTw3+q7IA+jjWYezrOAgRZJsARMuJq4/ccEtq4VFl+Fj6wIzDJGAjSLOeKV6n/rG6dBkB3z7XPuvQm64GXw/f1nCnZYyfVI9CxHqgXdDHScM7XjF1cpyOZUn1gTooQtoh6YKMRFz8v1w5X2qhTDa17t4y/ISUhWlOrJF2V/7TYgMd+cP7qo3qfEUjQEo8uL4yvfJInFlfN/xvA1N86JU4xiC9nh1kcXETP90VdApSiFsPkjTF82f7D9bubwecKqyu4t+vYi2RfnU+pgvmgM7+kCHIzgNdpY6Pr+7Ai//vPWDQoAdPU7+5PYk/IuoZatowlPR4iH17HTmkCkphwpvYqQ55ZxshCdOnY8edYOylLy3/lf9eZVV37iBJNIClRsroDI4ocYa06aHnjFV7tOa6dW1pLMrQEdvt3xhI1EjSbc9TMyprc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
